In [5]:
# Step 1: Import NumPy
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

zeroes_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeroes_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Try It 1
import numpy as np

years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

zeroes_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeroes_array)
print("Ones Array:\n", ones_array)

years_exp = np.append(years_exp, [12, 15])
new_salaries = np.array([[110, 120, 130], [140, 150, 160]])
salaries = np.concatenate((salaries, new_salaries), axis=0)

print("Updated Years of Experience:\n", years_exp)
print("Updated Salary Matrix:\n", salaries)

identity_matrix = np.eye(3)

print("3x3 Identity Matrix:\n", identity_matrix)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Updated Years of Experience:
 [ 1  3  5  7 10 12 15]
Updated Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]
 [140 150 160]]
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#2
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [16]:
# Try It 2

exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

exp_minus_1 = years_exp - 1
print("Years - 1:", exp_minus_1)

# Division: Cut all values in half
exp_div_2 = years_exp / 2
print("Years / 2:", exp_div_2)

Years + 5: [ 6  8 10 12 15 17 20]
Years * 2: [ 2  6 10 14 20 24 30]
Dot Product: 32
Years - 1: [ 0  2  4  6  9 11 14]
Years / 2: [0.5 1.5 2.5 3.5 5.  6.  7.5]


In [ ]:
#3
print("First year of experience:", years_exp[0])

print("Second column salaries:", salaries[0, :2]) # First two elemets of first row

print("Second column salaries:", salaries[:, 1])

print("Last year of experience:", years_exp[-1])


First year of experience: 1
Second column salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [17]:
# Try It 3
print("First year of experience:", years_exp[0])

print("Second column salaries:", salaries[0, :2]) # First two elemets of first row

print("Second column salaries:", salaries[:, 1])

print("Last year of experience:", years_exp[-1])

# Example: Extract a 2x2 subgroup from the top-left of the salaries matrix
# This takes rows 0 and 1, and columns 0 and 1
salary_subgroup = salaries[0:2, 0:2]
print("2x2 Salary Subgroup (Top-Left):\n", salary_subgroup)

# Example: Extract all rows but only the last two columns
last_two_cols = salaries[:, -2:]
print("Last two columns of all rows:\n", last_two_cols)


First year of experience: 1
Second column salaries: [50 60]
Second column salaries: [ 60  90 120 150]
Last year of experience: 15
2x2 Salary Subgroup (Top-Left):
 [[50 60]
 [80 90]]
Last two columns of all rows:
 [[ 60  70]
 [ 90 100]
 [120 130]
 [150 160]]


In [10]:
#4
#Step 1 Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

print("Transposed Array:\n", reshaped_exp.T)


Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [18]:
#Try It 4

#Step 1 Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

print("Transposed Array:\n", reshaped_exp.T)

# Create the base array with 6 elements
data = np.arange(1, 7) 

# Reshape into a 3x2 matrix (3 rows, 2 columns)
reshaped_3x2 = data.reshape(3, 2)
print("3x2 Matrix:\n", reshaped_3x2)

# Reshape into a 6x1 column vector
reshaped_column = data.reshape(6, 1)
print("\n6x1 Column Vector:\n", reshaped_column)

# Using -1 to let NumPy calculate the dimension automatically
# This reshapes it into 2 columns, and NumPy figures out it needs 3 rows
auto_reshaped = data.reshape(-1, 2)
print("\nAutomatically calculated 3x2 Matrix:\n", auto_reshaped)

# Transpose the 3x2 matrix into a 2x3 matrix
transposed_data = reshaped_3x2.T
print("\nTransposed (flipped) Matrix:\n", transposed_data)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
3x2 Matrix:
 [[1 2]
 [3 4]
 [5 6]]

6x1 Column Vector:
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

Automatically calculated 3x2 Matrix:
 [[1 2]
 [3 4]
 [5 6]]

Transposed (flipped) Matrix:
 [[1 3 5]
 [2 4 6]]


In [11]:
# 5 
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n:", salaries_with_bonus)

Salaries after bonus:
: [[ 55  70  85]
 [ 85 100 115]]


In [19]:
#Try It 5
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n:", salaries_with_bonus)

# Define a scaling factor (e.g., a 10% increase)
scaling_factor = 1.10

# Multiply the entire salaries matrix by the scalar
# This "broadcasts" the multiplication across every single element
scaled_salaries = salaries * scaling_factor

print("Original Salaries:\n", salaries)
print("\nSalaries after 10% increase:\n", scaled_salaries)

# Scale column 1 by 1.1, column 2 by 1.2, and column 3 by 1.3
column_scales = np.array([1.1, 1.2, 1.3])
scaled_by_col = salaries * column_scales

print("\nSalaries scaled by specific column factors:\n", scaled_by_col)

Salaries after bonus:
: [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]
 [145 160 175]]
Original Salaries:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]
 [140 150 160]]

Salaries after 10% increase:
 [[ 55.  66.  77.]
 [ 88.  99. 110.]
 [121. 132. 143.]
 [154. 165. 176.]]

Salaries scaled by specific column factors:
 [[ 55.  72.  91.]
 [ 88. 108. 130.]
 [121. 144. 169.]
 [154. 180. 208.]]


In [12]:
# 6
print("Mean experience:", np.mean(years_exp))

print("Std deviation of experience:", np.std(years_exp))

print("Max salary:", np.max(salaries), "Min salary", np.min(salaries))

print("Sum of all salaries:", np.sum(salaries))


Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary 50
Sum of all salaries: 450


In [20]:
#Try it 6

print("Mean experience:", np.mean(years_exp))

print("Std deviation of experience:", np.std(years_exp))

print("Max salary:", np.max(salaries), "Min salary", np.min(salaries))

print("Sum of all salaries:", np.sum(salaries))

# 1. Compute the Median
median_exp = np.median(years_exp)
print("Median Experience:", median_exp)

# 2. Compute the 25th and 75th Percentiles (Quartiles)
# This works for both 1D and 2D arrays
q1, q3 = np.percentile(salaries, [25, 75])

print(f"25th Percentile (Q1) of Salaries: {q1}")
print(f"75th Percentile (Q3) of Salaries: {q3}")

# 3. Median of salaries across a specific axis
# axis=0 calculates the median for each column
median_salary_cols = np.median(salaries, axis=0)
print("Median Salaries per column:", median_salary_cols)

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 160 Min salary 50
Sum of all salaries: 1260
Median Experience: 7.0
25th Percentile (Q1) of Salaries: 77.5
75th Percentile (Q3) of Salaries: 132.5
Median Salaries per column: [ 95. 105. 115.]


In [ ]:
# 7
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [21]:
#Try It 7
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

# Calculate the square root of all salaries
salary_sqrt = np.sqrt(salaries)
print("Square root of salaries:\n", salary_sqrt)

# Calculate the base-10 logarithm of salaries
# Useful for visualizing data that spans several orders of magnitude
salary_log10 = np.log10(salaries)
print("\nLog10 of salaries:\n", salary_log10)

# Define a custom function (e.g., finding the range: max - min)
def get_range(data_row):
    return np.max(data_row) - np.min(data_row)

# Apply the custom function along rows (axis=1)
# This calculates the salary range for each individual person
salary_ranges = np.apply_along_axis(get_range, 1, salaries)

print("\nSalary range (Max - Min) per person:", salary_ranges)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 360 450]
Square root of salaries:
 [[ 7.07106781  7.74596669  8.36660027]
 [ 8.94427191  9.48683298 10.        ]
 [10.48808848 10.95445115 11.40175425]
 [11.83215957 12.24744871 12.64911064]]

Log10 of salaries:
 [[1.69897    1.77815125 1.84509804]
 [1.90308999 1.95424251 2.        ]
 [2.04139269 2.07918125 2.11394335]
 [2.14612804 2.17609126 2.20411998]]

Salary range (Max - Min) per person: [20 20 20 20]


In [4]:
# 8
import pandas as pd
import numpy as np

data = np.random.randint(1, 50, size =(5, 3))

df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0  42  25  40
1  11  26  20
2  16   3  32
3  36   7  32
4  45   2  41
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  42  25  40  3.737670  5.000000
1  11  26  20  2.397895  5.099020
2  16   3  32  2.772589  1.732051
3  36   7  32  3.583519  2.645751
4  45   2  41  3.806662  1.414214
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.221628  0.878144  0.992171 -0.219291
Y      -0.221628  1.000000 -0.390488 -0.282428  0.994767
Z       0.878144 -0.390488  1.000000  0.891993 -0.408786
Log_X   0.992171 -0.282428  0.891993  1.000000 -0.271224
Sqrt_Y -0.219291  0.994767 -0.408786 -0.271224  1.000000


In [22]:
#Try it 8
import pandas as pd
import numpy as np

data = np.random.randint(1, 50, size =(5, 3))

df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

print("Correlation Matrix:\n", df_data.corr())

# Compute the mean for every column in the DataFrame
column_means = np.mean(df_data, axis=0)
print("Overall Column Means:\n", column_means)

# Compute the median for a specific column (e.g., column 'Z')
z_median = np.median(df_data['Z'])
print(f"\nMedian of Column Z: {z_median}")

# Create a new column by squaring the values of 'X'
df_data['X_Squared'] = np.square(df_data['X'])

# Apply exponential transformation to column 'Z'
df_data['Z_Exp'] = np.exp(df_data['Z'])

print("\nUpdated DataFrame with New Features:\n", df_data)

Generated Data:
     X   Y   Z
0  29   1  25
1   9  35  30
2  31  37   8
3  29  47  12
4   4  34  21
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  29   1  25  3.367296  1.000000
1   9  35  30  2.197225  5.916080
2  31  37   8  3.433987  6.082763
3  29  47  12  3.367296  6.855655
4   4  34  21  1.386294  5.830952
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000 -0.169270 -0.606888  0.983628 -0.257409
Y      -0.169270  1.000000 -0.485150 -0.168651  0.991915
Z      -0.606888 -0.485150  1.000000 -0.505757 -0.436703
Log_X   0.983628 -0.168651 -0.505757  1.000000 -0.256908
Sqrt_Y -0.257409  0.991915 -0.436703 -0.256908  1.000000
Overall Column Means:
 X         20.40000
Y         30.80000
Z         19.20000
Log_X      2.75042
Sqrt_Y     5.13709
dtype: float64

Median of Column Z: 21.0

Updated DataFrame with New Features:
     X   Y   Z     Log_X    Sqrt_Y  X_Squared         Z_Exp
0  29   1  25  3.367296  1.000000   

In [6]:
# 9 
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0  42  25  40  3.737670  5.000000
1  11  26  20  2.397895  5.099020
2  16   3  32  2.772589  1.732051
3  36   7  32  3.583519  2.645751
4  45   2  41  3.806662  1.414214
Summary Statistics:
                X          Y         Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.00000  5.000000  5.000000
mean   30.000000  12.600000  33.00000  3.259667  3.178207
std    15.508062  11.928956   8.42615  0.634915  1.767413
min    11.000000   2.000000  20.00000  2.397895  1.414214
25%    16.000000   3.000000  32.00000  2.772589  1.732051
50%    36.000000   7.000000  32.00000  3.583519  2.645751
75%    42.000000  25.000000  40.00000  3.737670  5.000000
max    45.000000  26.000000  41.00000  3.806662  5.099020
Column Means:
 X         30.000000
Y         12.600000
Z         33.000000
Log_X      3.259667
Sqrt_Y     3.178207
dtype: float64
Column Standard Deviations:
 X         15.508062
Y         11.928956


In [23]:
#Try it 9
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

# Create the Sum_XY column by adding columns X and Y
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']

# You can also create a product column for further review
df_imported['Product_XYZ'] = df_imported['X'] * df_imported['Y'] * df_imported['Z']

print("DataFrame with new calculated columns:\n", df_imported.head())

# Save to a new file named 'modified_data.csv'
# index=False prevents Pandas from writing the row numbers as a separate column
df_imported.to_csv('modified_data.csv', index=False)

print("Modified data has been successfully saved to 'modified_data.csv'.")

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  X_Squared         Z_Exp
0  29   1  25  3.367296  1.000000        841  7.200490e+10
1   9  35  30  2.197225  5.916080         81  1.068647e+13
2  31  37   8  3.433987  6.082763        961  2.980958e+03
3  29  47  12  3.367296  6.855655        841  1.627548e+05
4   4  34  21  1.386294  5.830952         16  1.318816e+09
Summary Statistics:
                X         Y          Z     Log_X    Sqrt_Y   X_Squared  \
count   5.000000   5.00000   5.000000  5.000000  5.000000    5.000000   
mean   20.400000  30.80000  19.200000  2.750420  5.137090  548.000000   
std    12.837445  17.44133   9.093954  0.921303  2.347954  459.178614   
min     4.000000   1.00000   8.000000  1.386294  1.000000   16.000000   
25%     9.000000  34.00000  12.000000  2.197225  5.830952   81.000000   
50%    29.000000  35.00000  21.000000  3.367296  5.916080  841.000000   
75%    29.000000  37.00000  25.000000  3.367296  6.082763  8

In [30]:
#10
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >=10, 'Senior', 'Junior')

grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data())

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,

TypeError: '>=' not supported between instances of 'str' and 'int'

In [31]:
#10 revised
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

# 1. Replace the text strings with numbers
df_clean['YearsCodePro'] = df_clean['YearsCodePro'].replace({'Less than 1 year': 0, 'More than 50 years': 51})

# 2. Convert the whole column to numbers (integers)
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'])

# 3. NOW run your logic
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Group by the new experience level and get the average salary
grouped_data = df_clean.groupby('ExperienceLevel')['ConvertedCompYearly'].mean().reset_index()
print("Formatted Grouped Data:\n", grouped_data)

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,

In [35]:
#Try it 10
df_kaggle = pd.read_csv('survey_results_public.csv')
print("Loaded Dataset:\n", df_kaggle.head())

df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedCompYearly']]
print("Subset of Data:\n", df_subset.head())

# 1. Replace the text strings with numbers
df_clean['YearsCodePro'] = df_clean['YearsCodePro'].replace({'Less than 1 year': 0, 'More than 50 years': 51})

# 2. Convert the whole column to numbers (integers)
df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'])

# 3. NOW run your logic
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Group by the new experience level and get the average salary
grouped_data = df_clean.groupby('ExperienceLevel')['ConvertedCompYearly'].mean().reset_index()
print("Formatted Grouped Data:\n", grouped_data)

# Grouping by Education Level and computing the median salary
grouped_edu = df_clean.groupby('EdLevel')['ConvertedCompYearly'].median().reset_index()

# Renaming the column for clarity
grouped_edu.columns = ['Education Level', 'Median Salary']
print("Median Salary by Education Level:\n", grouped_edu)

# Example for Standard Deviation
std_edu = df_clean.groupby('EdLevel')['ConvertedCompYearly'].std().reset_index()
print("\nSalary Standard Deviation by Education Level:\n", std_edu)

# Group by Country and calculate average salary
country_stats = df_clean.groupby('Country')['ConvertedCompYearly'].mean().reset_index()

# Sort by salary in descending order and take the top 10
top_10_countries = country_stats.sort_values(by='ConvertedCompYearly', ascending=False).head(10)

print("Top 10 Countries with Highest Average Compensation:\n", top_10_countries)

Loaded Dataset:
    ResponseId     Q120                      MainBranch              Age  \
0           1  I agree                   None of these  18-24 years old   
1           2  I agree  I am a developer by profession  25-34 years old   
2           3  I agree  I am a developer by profession  45-54 years old   
3           4  I agree  I am a developer by profession  25-34 years old   
4           5  I agree  I am a developer by profession  25-34 years old   

                                          Employment  \
0                                                NaN   
1                                Employed, full-time   
2                                Employed, full-time   
3                                Employed, full-time   
4  Employed, full-time;Independent contractor, fr...   

                             RemoteWork  \
0                                   NaN   
1                                Remote   
2  Hybrid (some remote, some in-person)   
3  Hybrid (some remote,